#!/bin/bash
# Fix IP addresses for K3s VMs via direct console commands
# This script will guide you through manual console fixes

PROXMOX_HOST="10.88.140.164"
K3S_USER="k3s"
K3S_PASSWORD="toor"

echo "================================================================"
echo "K3s VM IP Fix Guide - Manual Console Instructions"
echo "================================================================"
echo ""
echo "Since the VMs have IP conflicts, you need to use Proxmox console."
echo ""
echo "Open Proxmox web UI at: https://${PROXMOX_HOST}:8006"
echo ""
echo "================================================================"
echo "VM 303 - k3s-master02"
echo "================================================================"
echo "Current IP: 10.88.145.190"
echo "Target IP:  10.88.145.193"
echo ""
echo "Steps:"
echo "1. In Proxmox UI, click on VM 303 (k3s-master02)"
echo "2. Click 'Console' button"
echo "3. Login with: ${K3S_USER} / ${K3S_PASSWORD}"
echo "4. Run these commands:"
echo ""
echo "   sudo nano /etc/netplan/00-installer-config.yaml"
echo ""
echo "   Change the IP address line to:"
echo "        - 10.88.145.193/24"
echo ""
echo "   Save with Ctrl+O, Exit with Ctrl+X"
echo ""
echo "   sudo hostnamectl set-hostname k3s-master02"
echo "   sudo netplan apply"
echo "   sudo reboot"
echo ""
read -p "Press Enter when VM 303 is complete..."

echo ""
echo "================================================================"
echo "VM 304 - k3s-worker03"
echo "================================================================"
echo "Current IP: 10.88.145.191"
echo "Target IP:  10.88.145.194"
echo ""
echo "Steps:"
echo "1. In Proxmox UI, click on VM 304 (k3s-worker03)"
echo "2. Click 'Console' button"
echo "3. Login with: ${K3S_USER} / ${K3S_PASSWORD}"
echo "4. Run these commands:"
echo ""
echo "   sudo nano /etc/netplan/00-installer-config.yaml"
echo ""
echo "   Change the IP address line to:"
echo "        - 10.88.145.194/24"
echo ""
echo "   Save with Ctrl+O, Exit with Ctrl+X"
echo ""
echo "   sudo hostnamectl set-hostname k3s-worker03"
echo "   sudo netplan apply"
echo "   sudo reboot"
echo ""
read -p "Press Enter when VM 304 is complete..."

echo ""
echo "================================================================"
echo "VM 305 - k3s-worker04"
echo "================================================================"
echo "Current IP: 10.88.145.191"
echo "Target IP:  10.88.145.195"
echo ""
echo "Steps:"
echo "1. In Proxmox UI, click on VM 305 (k3s-worker04)"
echo "2. Click 'Console' button"
echo "3. Login with: ${K3S_USER} / ${K3S_PASSWORD}"
echo "4. Run these commands:"
echo ""
echo "   sudo nano /etc/netplan/00-installer-config.yaml"
echo ""
echo "   Change the IP address line to:"
echo "        - 10.88.145.195/24"
echo ""
echo "   Save with Ctrl+O, Exit with Ctrl+X"
echo ""
echo "   sudo hostnamectl set-hostname k3s-worker04"
echo "   sudo netplan apply"
echo "   sudo reboot"
echo ""
read -p "Press Enter when VM 305 is complete..."

echo ""
echo "================================================================"
echo "VM 306 - k3s-master03"
echo "================================================================"
echo "Current IP: 10.88.145.190"
echo "Target IP:  10.88.145.196"
echo ""
echo "Steps:"
echo "1. In Proxmox UI, click on VM 306 (k3s-master03)"
echo "2. Click 'Console' button"
echo "3. Login with: ${K3S_USER} / ${K3S_PASSWORD}"
echo "4. Run these commands:"
echo ""
echo "   sudo nano /etc/netplan/00-installer-config.yaml"
echo ""
echo "   Change the IP address line to:"
echo "        - 10.88.145.196/24"
echo ""
echo "   Save with Ctrl+O, Exit with Ctrl+X"
echo ""
echo "   sudo hostnamectl set-hostname k3s-master03"
echo "   sudo netplan apply"
echo "   sudo reboot"
echo ""
read -p "Press Enter when VM 306 is complete..."

echo ""
echo "================================================================"
echo "Verification"
echo "================================================================"
echo ""
echo "Now testing SSH connectivity to all new IPs..."
echo ""

for ip in 10.88.145.193 10.88.145.194 10.88.145.195 10.88.145.196; do
    echo -n "Testing ${ip}... "
    if ssh -o ConnectTimeout=5 -o StrictHostKeyChecking=no ${K3S_USER}@${ip} "echo 'OK'" 2>/dev/null; then
        echo "SUCCESS"
    else
        echo "FAILED - check configuration"
    fi
done

echo ""
echo "Manual IP fix guide complete!"
