#!/bin/bash
# Wazuh Agent Installation Script
# VM 903 (green-kali-server - 10.88.150.5)
# Auto-generated by Security Master

set -e
export DEBIAN_FRONTEND=noninteractive

WAZUH_MANAGER_IP="10.88.145.181"
WAZUH_MANAGER_PORT="31514"
WAZUH_VERSION="4.7.1"
AGENT_NAME="green-kali-server-vm903"

echo "Installing Wazuh Agent for ${AGENT_NAME}..."

# Stop if already running
systemctl stop wazuh-agent 2>/dev/null || true

# Download
curl -so /tmp/wazuh-agent.deb \
    "https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_${WAZUH_VERSION}-1_amd64.deb"

# Install
dpkg -i /tmp/wazuh-agent.deb 2>/dev/null || apt-get install -f -y >/dev/null 2>&1

# Configure
cat > /var/ossec/etc/ossec.conf <<'EOF'
<ossec_config>
  <client>
    <server>
      <address>10.88.145.181</address>
      <port>31514</port>
      <protocol>tcp</protocol>
    </server>
    <config-profile>debian, debian10</config-profile>
    <notify_time>10</notify_time>
    <time-reconnect>60</time-reconnect>
    <auto_restart>yes</auto_restart>
  </client>
  <client_buffer>
    <disabled>no</disabled>
    <queue_size>5000</queue_size>
    <events_per_second>500</events_per_second>
  </client_buffer>
  <logging>
    <log_format>plain</log_format>
  </logging>
  <wodle name="syscollector">
    <disabled>no</disabled>
    <interval>1h</interval>
    <scan_on_start>yes</scan_on_start>
  </wodle>
  <sca>
    <enabled>yes</enabled>
    <scan_on_start>yes</scan_on_start>
    <interval>12h</interval>
  </sca>
</ossec_config>
EOF

echo "${AGENT_NAME}" > /var/ossec/etc/agent-name

# Start
systemctl daemon-reload
systemctl enable wazuh-agent
systemctl restart wazuh-agent
sleep 5

if systemctl is-active --quiet wazuh-agent; then
    echo "SUCCESS: ${AGENT_NAME} connected to ${WAZUH_MANAGER_IP}:${WAZUH_MANAGER_PORT}"
    /var/ossec/bin/wazuh-control info 2>/dev/null || true
else
    echo "ERROR: Agent failed to start"
    systemctl status wazuh-agent --no-pager
    exit 1
fi
