#!/bin/bash
# Generate Wazuh Agent Deployment Snippets for each VM
# Security Master - Deployment Snippet Generator

set -euo pipefail

OUTPUT_DIR="/Users/ryandahlberg/Projects/cortex/coordination/masters/security/deployment-snippets"
mkdir -p "$OUTPUT_DIR"

echo "========================================="
echo "Generating Wazuh Deployment Snippets"
echo "========================================="
echo ""

# Define all VMs to deploy to
declare -a VMS=(
    "310:k3s-master-vm:10.88.145.180"
    "311:k3s-worker-1-vm:10.88.145.181"
    "312:k3s-worker-2-vm:10.88.145.182"
    "900:red-kali-server:10.88.150.2"
    "901:blue-kali-server:10.88.150.3"
    "902:purple-kali-server:10.88.150.4"
    "903:green-kali-server:10.88.150.5"
    "200:claude-code-agent:10.88.140.200"
)

# Wazuh Manager configuration
WAZUH_MANAGER_IP="10.88.145.181"
WAZUH_MANAGER_PORT="31514"
WAZUH_VERSION="4.7.1"

for vm_config in "${VMS[@]}"; do
    IFS=':' read -r VMID VM_NAME VM_IP <<< "$vm_config"
    AGENT_NAME="${VM_NAME}-vm${VMID}"

    # Create individual install script for this VM
    cat > "${OUTPUT_DIR}/install-wazuh-${VMID}.sh" <<'EOFSCRIPT'
#!/bin/bash
# Wazuh Agent Installation Script
# VM_PLACEHOLDER
# Auto-generated by Security Master

set -e
export DEBIAN_FRONTEND=noninteractive

WAZUH_MANAGER_IP="MANAGER_IP_PLACEHOLDER"
WAZUH_MANAGER_PORT="MANAGER_PORT_PLACEHOLDER"
WAZUH_VERSION="VERSION_PLACEHOLDER"
AGENT_NAME="AGENT_NAME_PLACEHOLDER"

echo "Installing Wazuh Agent for ${AGENT_NAME}..."

# Stop if already running
systemctl stop wazuh-agent 2>/dev/null || true

# Download
curl -so /tmp/wazuh-agent.deb \
    "https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_${WAZUH_VERSION}-1_amd64.deb"

# Install
dpkg -i /tmp/wazuh-agent.deb 2>/dev/null || apt-get install -f -y >/dev/null 2>&1

# Configure
cat > /var/ossec/etc/ossec.conf <<'EOF'
<ossec_config>
  <client>
    <server>
      <address>MANAGER_IP_PLACEHOLDER</address>
      <port>MANAGER_PORT_PLACEHOLDER</port>
      <protocol>tcp</protocol>
    </server>
    <config-profile>debian, debian10</config-profile>
    <notify_time>10</notify_time>
    <time-reconnect>60</time-reconnect>
    <auto_restart>yes</auto_restart>
  </client>
  <client_buffer>
    <disabled>no</disabled>
    <queue_size>5000</queue_size>
    <events_per_second>500</events_per_second>
  </client_buffer>
  <logging>
    <log_format>plain</log_format>
  </logging>
  <wodle name="syscollector">
    <disabled>no</disabled>
    <interval>1h</interval>
    <scan_on_start>yes</scan_on_start>
  </wodle>
  <sca>
    <enabled>yes</enabled>
    <scan_on_start>yes</scan_on_start>
    <interval>12h</interval>
  </sca>
</ossec_config>
EOF

echo "${AGENT_NAME}" > /var/ossec/etc/agent-name

# Start
systemctl daemon-reload
systemctl enable wazuh-agent
systemctl restart wazuh-agent
sleep 5

if systemctl is-active --quiet wazuh-agent; then
    echo "SUCCESS: ${AGENT_NAME} connected to ${WAZUH_MANAGER_IP}:${WAZUH_MANAGER_PORT}"
    /var/ossec/bin/wazuh-control info 2>/dev/null || true
else
    echo "ERROR: Agent failed to start"
    systemctl status wazuh-agent --no-pager
    exit 1
fi
EOFSCRIPT

    # Replace placeholders
    sed -i.bak \
        -e "s/VM_PLACEHOLDER/VM ${VMID} (${VM_NAME} - ${VM_IP})/g" \
        -e "s/MANAGER_IP_PLACEHOLDER/${WAZUH_MANAGER_IP}/g" \
        -e "s/MANAGER_PORT_PLACEHOLDER/${WAZUH_MANAGER_PORT}/g" \
        -e "s/VERSION_PLACEHOLDER/${WAZUH_VERSION}/g" \
        -e "s/AGENT_NAME_PLACEHOLDER/${AGENT_NAME}/g" \
        "${OUTPUT_DIR}/install-wazuh-${VMID}.sh"

    rm -f "${OUTPUT_DIR}/install-wazuh-${VMID}.sh.bak"
    chmod +x "${OUTPUT_DIR}/install-wazuh-${VMID}.sh"

    # Create curl one-liner for remote execution
    cat > "${OUTPUT_DIR}/deploy-${VMID}-oneliner.txt" <<EOF
# Deploy to VM ${VMID} (${VM_NAME} - ${VM_IP})
# Copy and paste this one-liner into the VM's terminal as root:

curl -sSL 'https://raw.githubusercontent.com/your-repo/cortex/main/scripts/security/deployment-snippets/install-wazuh-${VMID}.sh' | bash

# Or if you have the script locally:
# bash /path/to/install-wazuh-${VMID}.sh

# Or base64-encoded inline execution:
echo "$(base64 < ${OUTPUT_DIR}/install-wazuh-${VMID}.sh)" | base64 -d | bash
EOF

    echo "✓ Generated scripts for VM ${VMID} (${VM_NAME})"
done

# Create master deployment checklist
cat > "${OUTPUT_DIR}/DEPLOYMENT-CHECKLIST.md" <<'EOF'
# Wazuh Agent Deployment Checklist

## Deployment Status

| VM ID | Name | IP | Status | Notes |
|-------|------|----|----|-------|
| 310 | k3s-master-vm | 10.88.145.180 | ⬜ Pending | K3s Master Node |
| 311 | k3s-worker-1-vm | 10.88.145.181 | ⬜ Pending | K3s Worker 1 |
| 312 | k3s-worker-2-vm | 10.88.145.182 | ⬜ Pending | K3s Worker 2 |
| 900 | red-kali-server | 10.88.150.2 | ⬜ Pending | Red Team |
| 901 | blue-kali-server | 10.88.150.3 | ⬜ Pending | Blue Team |
| 902 | purple-kali-server | 10.88.150.4 | ⬜ Pending | Purple Team |
| 903 | green-kali-server | 10.88.150.5 | ⬜ Pending | Green Team |
| 200 | claude-code-agent | 10.88.140.200 | ⬜ Pending | Infrastructure |

## Deployment Methods

### Method 1: SSH (if configured)
```bash
ssh root@<VM_IP> 'bash -s' < install-wazuh-<VMID>.sh
```

### Method 2: Manual Execution
1. SSH or console into the VM
2. Copy the content of `install-wazuh-<VMID>.sh`
3. Execute as root

### Method 3: HTTP Download
```bash
curl -sSL <URL_TO_SCRIPT> | bash
```

### Method 4: Base64 Inline
Use the one-liner from `deploy-<VMID>-oneliner.txt`

## Verification

After deployment, verify agent registration:
```bash
# On Wazuh Manager
curl -k -u admin:SecurePass -X GET \
    "https://10.88.145.181:55000/agents?pretty=true"
```

## Post-Deployment

- [ ] All 8 agents registered
- [ ] All agents showing as active
- [ ] Security events flowing to manager
- [ ] Dashboard updated with new agents
- [ ] Security metrics updated
EOF

# Create verification script
cat > "${OUTPUT_DIR}/../verify-wazuh-agents.sh" <<'EOFVERIFY'
#!/bin/bash
# Verify Wazuh Agent Deployments
# Security Master - Verification Script

set -e

WAZUH_MANAGER_IP="10.88.145.181"
WAZUH_MANAGER_PORT="55000"
WAZUH_MANAGER_USER="${WAZUH_USER:-admin}"
WAZUH_MANAGER_PASS="${WAZUH_PASS:-SecurePass}"

echo "========================================="
echo "Wazuh Agent Verification"
echo "========================================="
echo "Manager: ${WAZUH_MANAGER_IP}:${WAZUH_MANAGER_PORT}"
echo ""

# Query all agents
echo "Querying registered agents..."
echo ""

AGENTS=$(curl -k -s -u "${WAZUH_MANAGER_USER}:${WAZUH_MANAGER_PASS}" \
    "https://${WAZUH_MANAGER_IP}:${WAZUH_MANAGER_PORT}/agents?pretty=true&limit=100")

if echo "$AGENTS" | jq -e '.data.total_affected_items' >/dev/null 2>&1; then
    TOTAL=$(echo "$AGENTS" | jq -r '.data.total_affected_items')
    echo "Total agents registered: ${TOTAL}"
    echo ""

    if [ "$TOTAL" -gt 0 ]; then
        echo "Agent Details:"
        echo "$AGENTS" | jq -r '.data.affected_items[] | "  [\(.id)] \(.name) - \(.ip) - Status: \(.status)"'
    fi
else
    echo "ERROR: Failed to query agents"
    echo "$AGENTS"
    exit 1
fi

echo ""
echo "Verification complete!"
EOFVERIFY

chmod +x "${OUTPUT_DIR}/../verify-wazuh-agents.sh"

echo ""
echo "========================================="
echo "Deployment Snippets Generated!"
echo "========================================="
echo "Location: ${OUTPUT_DIR}"
echo ""
echo "Files created:"
ls -lh "$OUTPUT_DIR"
echo ""
echo "Next steps:"
echo "1. Review DEPLOYMENT-CHECKLIST.md"
echo "2. Deploy agents using preferred method"
echo "3. Run verify-wazuh-agents.sh to confirm"
echo ""
